### ISSUE TITLE
uarm_library.h vs. UF_uArm_Metal.h

### ISSUE THREAD

**Issue by anudels** [uArm-Developer/UArmForArduino#15]
Hi, I am wondering if I only need the uarm_library.h file or if I also need the UF_uArm_Metal.h file. I want to do a calibration but the uarm_library.h file does not have a calibration function while the UF_uArm_Metal.h file does have a calibration function. Could someone please explain which libraries need to be used/ are the currently supported ones and which libraries are out of date/ no longer supported.

**Comment by dcorboy** [comment]
You should use the files in uArm-Developer/UArmForArduino (only). The "Metal" version is out of date and uses a _different_ calibration scheme (but may still support the old learning mode and some other appy-stuff).

We had some problems with the master code tree but they should all be resolved now and if you pull the latest tip, you will get the correct calibration sketch.

So use the new libraries and we are here to help if you have issues. :)
