### ISSUE TITLE
Changes in EEPROM.h?

### ISSUE THREAD

**Issue by WaldoPepper** [uArm-Developer/UArmForArduino#16]
Hi, I just tried to use the lib in Arduino 1.7.10 and got the following error message:

UArmForArduino-master\uarm_library.cpp:200:12: error: 'class EEPROMClass' has no member named 'get'
     EEPROM.get(MANUAL_OFFSET_ADDRESS + servo_num * sizeof(manual_servo_offset), manual_servo_offset);

EEPROM.h in 1.7.10 does export a "write" and  a "read" method, can you please check if this changed since you last committed you library?

Kai

**Comment by UFactory-Alex** [comment]
Hi @WaldoPepper , I tried v1.6.8, It's working. You could refer this link for [EEPROMGet](https://www.arduino.cc/en/Reference/EEPROMGet).
