### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by AshleyF** [uArm-Developer/UArmForArduino#18]
There is no license file. What is the license for using this code?
Thanks!

**Comment by UFactory** [comment]
@AshleyF That's a good question, We are still thinking about the license. May be GPL is the best choice for us, as we are a open-source hardware company.
Also any suggestion would be welcome for the license.

**Comment by AshleyF** [comment]
Ah, I notice actually that (while there's no license file) some of the source files say LGPL. Good to know.
Our legal guys would be happier with MIT, BSD or Apache, but hey...

**Comment by apockill** [comment]
Just curious- would GPL be better?
