### ISSUE TITLE
Buzzer documentation is incorrect, and it has been changed for the worse

### ISSUE THREAD

**Issue by apockill** [uArm-Developer/UArmForArduino#22]
When I do:

\[sBuzzF1500T1]  (or any combination)

The output is always F1.

I noticed implementation has been changed to use a new function, 'alert'.
Please switch it back to the default arduino "tone" function to activate the buzz, and the "noTone" function to end the buzz. 
This was already implemented and working, and for some reason has been changed.

The reason this is a problem is because this new implementation halts all code while the buzzer is ringing. It is HIGHLY important that the buzzer does not take time away from the communication protocol. By using "tone" and "noTone" you are able to do other processing while the buzzer is sounding. This entire communication protocol should be focused on speed, and reliability of communications. If using the buzzer halts communication, it defeats the whole purpose of this protocol.

**Comment by UFactory-Alex** [comment]
roll back to tone().
