### ISSUE TITLE
Inconsistent argument names in protocol

### ISSUE THREAD

**Issue by apockill** [uArm-Developer/UArmForArduino#23]
The protocol is inconsistent:

[sSerN#V#]  Where N is the servo number
[sAttS#]  Where S is the servo number
[sDetS#]  Where S is the servo number

Can we make them both be N or S? I want to keep things consistent in the protocol.

**Comment by TonyLeheng** [comment]
Yeah, I think we should make them to N which means number :)

**Comment by apockill** [comment]
I agree.

**Comment by apockill** [comment]
Fixed by @UFactory-Alex
