### ISSUE TITLE
[gCrd] is innaccurate. Issue with protocol or calibration?

### ISSUE THREAD

**Issue by apockill** [uArm-Developer/UArmForArduino#24]
[gCrd] is returning very innacurate results... About 2 cm off at all times. Is this just due to calibration issues?

**Comment by UFactory-Alex** [comment]
It caused by the servo offset. I disable the offset temporary, I test the accuracy less than 1cm. 
If the servos assembled in a correct angle, it won't effect the uArm coordinate. You could try this first, We will fix offset issue latter.

**Comment by apockill** [comment]
Fixed by @UFactory-Alex
