### ISSUE TITLE
When moving from one point to another, robot will stop halfway

### ISSUE THREAD

**Issue by apockill** [uArm-Developer/UArmForArduino#26]
If you move from point Xa Ya Za to Xb Yb Zb and there is some point inbetween that is unreachable, the robot will stop moving at that point, instead of skipping to the next reachable point and moving there.

This causes big issues, since the robot clearly can reach it's final destination, but is arbitrarily stopping halfway. This system is also very buggy, because it will incorrectly say that a position is unreachable. This didn't used to be an issue- the robot would always get to it's final destination. Now it just... stops. Is it possible to reverse this change?

Proposed change: 
If a certain XYZ step is unreachable, skip to the next point, or jump to the destination anyways. Or just go back to whatever system was being used before.

**Comment by TonyLeheng** [comment]
We know this issue, we are trying to remove the range limit as much as possible, and also improve the trajectory planning system : )
